apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: n8n
spec:
  ports:
    - port: "${DB_POSTGRESDB_PORT}"
      targetPort: "${DB_POSTGRESDB_PORT}"
  selector:
    app: postgres
  clusterIP: None
